export * from './event/event.component'
export * from './event-detail/event-detail.component'
export * from './modal-to-edit/modal-to-edit.component'
export * from './new-event/new-event.component'
export * from './modal-to-change-photo/modal-to-change-photo.component'
export * from './modal-to-change-pwd/modal-to-change-pwd.component'